name: Sphinx Documentation

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ahmad88me/sphinx-docs-action@bf593596505b1147dc970de7fc802d3ad4e80a05
        with:
          python-version: '3.8'
          git-username: 'ahmad88me'
          git-email: 'ahmad88me@gmail.com'
          project-path: 'src'
          commit-message: 'update docs'
          files-pattern: 'examples/*example*.py'
          github-token: ${{ secrets.GITHUB_TOKEN }}

