name: Sphinx Documentation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ahmad88me/sphinx-docs-action@v0.4
        with:
          python-version: '3.8'
          git-username: 'ahmad88me'
          git-email: 'ahmad88me@gmail.com'
          project-path: 'src'
          files-pattern: 'examples/*example*.py'
          commit-message: 'update docs'
          github-token: ${{ secrets.GITHUB_TOKEN }}

