name: Sphinx Documentation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ahmad88me/sphinx-docs-action@729326fc9382f724cfad2e0a3cd6d9224fcd646a
        with:
          python-version: '3.8'
          git-username: 'ahmad88me'
          git-email: 'ahmad88me@gmail.com'
          project-path: 'src'
          readme: README-pypi.md
          commit-message: 'update docs'
          files-pattern: 'examples/*example*.py'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: --debug
