name: Sphinx Documentation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ahmad88me/sphinx-docs-action@v0.6
        with:
          python-version: '3.8'
          git-username: 'ahmad88me'
          git-email: 'ahmad88me@gmail.com'
          project-path: 'src'
          commit-message: 'update docs'
          files-pattern: 'examples/*example*.py'
          github-token: ${{ secrets.GITHUB_TOKEN }}

